// Lista local de ciudades y países para autocompletado
// Puedes ampliarla según tus necesidades
export const ciudadesPaises = [
  { value: 'Bogotá, Colombia', label: 'Bogotá, Colombia' },
  { value: 'Medellín, Colombia', label: 'Medellín, Colombia' },
  { value: 'Cali, Colombia', label: 'Cali, Colombia' },
  { value: 'Barranquilla, Colombia', label: 'Barranquilla, Colombia' },
  { value: 'Cartagena, Colombia', label: 'Cartagena, Colombia' },
  { value: 'Cúcuta, Colombia', label: 'Cúcuta, Colombia' },
  { value: 'Soacha, Colombia', label: 'Soacha, Colombia' },
  { value: 'Soledad, Colombia', label: 'Soledad, Colombia' },
  { value: 'Bucaramanga, Colombia', label: 'Bucaramanga, Colombia' },
  { value: 'Bello, Colombia', label: 'Bello, Colombia' },
  { value: 'Villavicencio, Colombia', label: 'Villavicencio, Colombia' },
  { value: 'Ibagué, Colombia', label: 'Ibagué, Colombia' },
  { value: 'Santa Marta, Colombia', label: 'Santa Marta, Colombia' },
  { value: 'Valledupar, Colombia', label: 'Valledupar, Colombia' },
  { value: 'Montería, Colombia', label: 'Montería, Colombia' },
  { value: 'Pereira, Colombia', label: 'Pereira, Colombia' },
  { value: 'Manizales, Colombia', label: 'Manizales, Colombia' },
  { value: 'Pasto, Colombia', label: 'Pasto, Colombia' },
  { value: 'Neiva, Colombia', label: 'Neiva, Colombia' },
  { value: 'Armenia, Colombia', label: 'Armenia, Colombia' },
  { value: 'Popayán, Colombia', label: 'Popayán, Colombia' },
  { value: 'Sincelejo, Colombia', label: 'Sincelejo, Colombia' },
  { value: 'Itagüí, Colombia', label: 'Itagüí, Colombia' },
  { value: 'Floridablanca, Colombia', label: 'Floridablanca, Colombia' },
  { value: 'Envigado, Colombia', label: 'Envigado, Colombia' },
  { value: 'Tuluá, Colombia', label: 'Tuluá, Colombia' },
  { value: 'Dosquebradas, Colombia', label: 'Dosquebradas, Colombia' },
  { value: 'Tumaco, Colombia', label: 'Tumaco, Colombia' },
  { value: 'Riohacha, Colombia', label: 'Riohacha, Colombia' },
  { value: 'Palmira, Colombia', label: 'Palmira, Colombia' },
  { value: 'Buenaventura, Colombia', label: 'Buenaventura, Colombia' },
  { value: 'Girón, Colombia', label: 'Girón, Colombia' },
  { value: 'Malambo, Colombia', label: 'Malambo, Colombia' },
  { value: 'Magangué, Colombia', label: 'Magangué, Colombia' },
  { value: 'Sogamoso, Colombia', label: 'Sogamoso, Colombia' },
  { value: 'Facatativá, Colombia', label: 'Facatativá, Colombia' },
  { value: 'Chía, Colombia', label: 'Chía, Colombia' },
  { value: 'Jamundí, Colombia', label: 'Jamundí, Colombia' },
  { value: 'Zipaquirá, Colombia', label: 'Zipaquirá, Colombia' },
  { value: 'Fusagasugá, Colombia', label: 'Fusagasugá, Colombia' },
  { value: 'Rionegro, Colombia', label: 'Rionegro, Colombia' },
  { value: 'Yopal, Colombia', label: 'Yopal, Colombia' },
  { value: 'Ciénaga, Colombia', label: 'Ciénaga, Colombia' },
  { value: 'Cajicá, Colombia', label: 'Cajicá, Colombia' },
  { value: 'Lorica, Colombia', label: 'Lorica, Colombia' },
  { value: 'Madrid, Colombia', label: 'Madrid, Colombia' },
  { value: 'Maicao, Colombia', label: 'Maicao, Colombia' },
  { value: 'Apartadó, Colombia', label: 'Apartadó, Colombia' },
  { value: 'Piedecuesta, Colombia', label: 'Piedecuesta, Colombia' },
  { value: 'Cartago, Colombia', label: 'Cartago, Colombia' },
  { value: 'Quibdó, Colombia', label: 'Quibdó, Colombia' },
  { value: 'Turbo, Colombia', label: 'Turbo, Colombia' },
  { value: 'Caldas, Colombia', label: 'Caldas, Colombia' },
  { value: 'La Dorada, Colombia', label: 'La Dorada, Colombia' },
  { value: 'Pitalito, Colombia', label: 'Pitalito, Colombia' },
  { value: 'Sabanalarga, Colombia', label: 'Sabanalarga, Colombia' },
  { value: 'El Carmen de Bolívar, Colombia', label: 'El Carmen de Bolívar, Colombia' },
  { value: 'Cereté, Colombia', label: 'Cereté, Colombia' },
  { value: 'Ipiales, Colombia', label: 'Ipiales, Colombia' },
  { value: 'San Andrés, Colombia', label: 'San Andrés, Colombia' },
  { value: 'Leticia, Colombia', label: 'Leticia, Colombia' },
  { value: 'Mocoa, Colombia', label: 'Mocoa, Colombia' },
  { value: 'Mitú, Colombia', label: 'Mitú, Colombia' },
  { value: 'Puerto Carreño, Colombia', label: 'Puerto Carreño, Colombia' },
  { value: 'Inírida, Colombia', label: 'Inírida, Colombia' },
  { value: 'San José del Guaviare, Colombia', label: 'San José del Guaviare, Colombia' },
  { value: 'Puerto Asís, Colombia', label: 'Puerto Asís, Colombia' },
  { value: 'Arauca, Colombia', label: 'Arauca, Colombia' },
  { value: 'Yumbo, Colombia', label: 'Yumbo, Colombia' },
  { value: 'Florida, Colombia', label: 'Florida, Colombia' },
  { value: 'Sabaneta, Colombia', label: 'Sabaneta, Colombia' },
  { value: 'Mosquera, Colombia', label: 'Mosquera, Colombia' },
  { value: 'Funza, Colombia', label: 'Funza, Colombia' },
  { value: 'Copacabana, Colombia', label: 'Copacabana, Colombia' },
  { value: 'La Estrella, Colombia', label: 'La Estrella, Colombia' },
  { value: 'Girardot, Colombia', label: 'Girardot, Colombia' },
  { value: 'Chigorodó, Colombia', label: 'Chigorodó, Colombia' },
  { value: 'Cota, Colombia', label: 'Cota, Colombia' },
  { value: 'Sopó, Colombia', label: 'Sopó, Colombia' },
  { value: 'Tocancipá, Colombia', label: 'Tocancipá, Colombia' },
  { value: 'La Ceja, Colombia', label: 'La Ceja, Colombia' },
  { value: 'El Espinal, Colombia', label: 'El Espinal, Colombia' },
  { value: 'Sonsón, Colombia', label: 'Sonsón, Colombia' },
  { value: 'Guarne, Colombia', label: 'Guarne, Colombia' },
  { value: 'Sibaté, Colombia', label: 'Sibaté, Colombia' },
  { value: 'Candelaria, Colombia', label: 'Candelaria, Colombia' },
  { value: 'Puerto Colombia, Colombia', label: 'Puerto Colombia, Colombia' },
  { value: 'Turbaco, Colombia', label: 'Turbaco, Colombia' },
  { value: 'Villa del Rosario, Colombia', label: 'Villa del Rosario, Colombia' },
  { value: 'El Bagre, Colombia', label: 'El Bagre, Colombia' },
  { value: 'Sahagún, Colombia', label: 'Sahagún, Colombia' },
  { value: 'Ocaña, Colombia', label: 'Ocaña, Colombia' },
  { value: 'Chinchiná, Colombia', label: 'Chinchiná, Colombia' },
  { value: 'Pamplona, Colombia', label: 'Pamplona, Colombia' },
  { value: 'Garzón, Colombia', label: 'Garzón, Colombia' },
  { value: 'El Zulia, Colombia', label: 'El Zulia, Colombia' },
  { value: 'Puerto Tejada, Colombia', label: 'Puerto Tejada, Colombia' },
  { value: 'Tierralta, Colombia', label: 'Tierralta, Colombia' },
  { value: 'Sampués, Colombia', label: 'Sampués, Colombia' },
  { value: 'San Vicente del Caguán, Colombia', label: 'San Vicente del Caguán, Colombia' },
  { value: 'Ciénaga de Oro, Colombia', label: 'Ciénaga de Oro, Colombia' },
  { value: 'Puerto Boyacá, Colombia', label: 'Puerto Boyacá, Colombia' },
  { value: 'Aguachica, Colombia', label: 'Aguachica, Colombia' },
  { value: 'El Banco, Colombia', label: 'El Banco, Colombia' },
  { value: 'San Gil, Colombia', label: 'San Gil, Colombia' },
  { value: 'Tame, Colombia', label: 'Tame, Colombia' },
  { value: 'Caucasia, Colombia', label: 'Caucasia, Colombia' },
  { value: 'Puerto Berrío, Colombia', label: 'Puerto Berrío, Colombia' },
  { value: 'La Virginia, Colombia', label: 'La Virginia, Colombia' },
  { value: 'El Retiro, Colombia', label: 'El Retiro, Colombia' },
  { value: 'San Juan de Pasto, Colombia', label: 'San Juan de Pasto, Colombia' },
  { value: 'Guadalajara de Buga, Colombia', label: 'Guadalajara de Buga, Colombia' },
  { value: 'Carmen de Viboral, Colombia', label: 'Carmen de Viboral, Colombia' },
  { value: 'Sabaneta, Colombia', label: 'Sabaneta, Colombia' },
  { value: 'Tuluá, Colombia', label: 'Tuluá, Colombia' },
  { value: 'Riosucio, Colombia', label: 'Riosucio, Colombia' },
  { value: 'Guarne, Colombia', label: 'Guarne, Colombia' },
  { value: 'El Colegio, Colombia', label: 'El Colegio, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'Puerto Wilches, Colombia', label: 'Puerto Wilches, Colombia' },
  { value: 'La Unión, Colombia', label: 'La Unión, Colombia' },
  { value: 'Cumaral, Colombia', label: 'Cumaral, Colombia' },
  { value: 'San Marcos, Colombia', label: 'San Marcos, Colombia' },
  { value: 'El Doncello, Colombia', label: 'El Doncello, Colombia' },
  { value: 'San Onofre, Colombia', label: 'San Onofre, Colombia' },
  { value: 'Puerto López, Colombia', label: 'Puerto López, Colombia' },
  { value: 'San Benito Abad, Colombia', label: 'San Benito Abad, Colombia' },
  { value: 'Puerto Nare, Colombia', label: 'Puerto Nare, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'El Charco, Colombia', label: 'El Charco, Colombia' },
  { value: 'San Jacinto, Colombia', label: 'San Jacinto, Colombia' },
  { value: 'Puerto Gaitán, Colombia', label: 'Puerto Gaitán, Colombia' },
  { value: 'San Martín, Colombia', label: 'San Martín, Colombia' },
  { value: 'El Tarra, Colombia', label: 'El Tarra, Colombia' },
  { value: 'San Bernardo del Viento, Colombia', label: 'San Bernardo del Viento, Colombia' },
  { value: 'Puerto Concordia, Colombia', label: 'Puerto Concordia, Colombia' },
  { value: 'San Carlos, Colombia', label: 'San Carlos, Colombia' },
  { value: 'San José de Cúcuta, Colombia', label: 'San José de Cúcuta, Colombia' },
  { value: 'San Vicente, Colombia', label: 'San Vicente, Colombia' },
  { value: 'San Juan Nepomuceno, Colombia', label: 'San Juan Nepomuceno, Colombia' },
  { value: 'San Pedro de Urabá, Colombia', label: 'San Pedro de Urabá, Colombia' },
  { value: 'San Andrés de Sotavento, Colombia', label: 'San Andrés de Sotavento, Colombia' },
  { value: 'San Sebastián de Mariquita, Colombia', label: 'San Sebastián de Mariquita, Colombia' },
  { value: 'San Antero, Colombia', label: 'San Antero, Colombia' },
  { value: 'San Juan del Cesar, Colombia', label: 'San Juan del Cesar, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Roque, Colombia', label: 'San Roque, Colombia' },
  { value: 'San Alberto, Colombia', label: 'San Alberto, Colombia' },
  { value: 'San Gil, Colombia', label: 'San Gil, Colombia' },
  { value: 'San Pablo de Borbur, Colombia', label: 'San Pablo de Borbur, Colombia' },
  { value: 'San Rafael, Colombia', label: 'San Rafael, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San José de Pare, Colombia', label: 'San José de Pare, Colombia' },
  { value: 'San Cayetano, Colombia', label: 'San Cayetano, Colombia' },
  { value: 'San Pedro de los Milagros, Colombia', label: 'San Pedro de los Milagros, Colombia' },
  { value: 'San Antonio, Colombia', label: 'San Antonio, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Bernardo, Colombia', label: 'San Bernardo, Colombia' },
  { value: 'San Zenón, Colombia', label: 'San Zenón, Colombia' },
  { value: 'San Luis, Colombia', label: 'San Luis, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Miguel, Colombia', label: 'San Miguel, Colombia' },
  { value: 'San Francisco, Colombia', label: 'San Francisco, Colombia' },
  { value: 'San Eduardo, Colombia', label: 'San Eduardo, Colombia' },
  { value: 'San Sebastián, Colombia', label: 'San Sebastián, Colombia' },
  { value: 'San Benito, Colombia', label: 'San Benito, Colombia' },
  { value: 'San Cayetano, Colombia', label: 'San Cayetano, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juanito, Colombia', label: 'San Juanito, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Antonio del Tequendama, Colombia', label: 'San Antonio del Tequendama, Colombia' },
  { value: 'San José de Miranda, Colombia', label: 'San José de Miranda, Colombia' },
  { value: 'San Juan de Río Seco, Colombia', label: 'San Juan de Río Seco, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Urabá, Colombia', label: 'San Juan de Urabá, Colombia' },
  { value: 'San José de la Montaña, Colombia', label: 'San José de la Montaña, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Pasto, Colombia', label: 'San Juan de Pasto, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
  { value: 'San Pedro, Colombia', label: 'San Pedro, Colombia' },
  { value: 'San Juan de Betulia, Colombia', label: 'San Juan de Betulia, Colombia' },
  { value: 'San Pablo, Colombia', label: 'San Pablo, Colombia' },
  { value: 'San Juan de Arama, Colombia', label: 'San Juan de Arama, Colombia' },
];
